example:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: feda
    username: root
    password: Aa123456!
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.qq.com
    port: 587
    username: 1009216181@qq.com
    password: hiuijfuvcqegbbef
  nacos:
    server-addr: 10.112.19.119:8848
  sentinel:
    dashboard: localhost:8090
